// Code generated by "stringer -type=Format"; DO NOT EDIT.

package surface

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FormatARGB32-0]
	_ = x[FormatRGB24-1]
	_ = x[FormatA8-2]
	_ = x[FormatA1-3]
	_ = x[FormatRGB16_565-4]
	_ = x[FormatRGB30-5]
	_ = x[FormatRGB96F-6]
	_ = x[FormatRGBA128F-7]
	_ = x[FormatInvalid - -1]
}

const _Format_name = "FormatInvalidFormatARGB32FormatRGB24FormatA8FormatA1FormatRGB16_565FormatRGB30FormatRGB96FFormatRGBA128F"

var _Format_index = [...]uint8{0, 13, 25, 36, 44, 52, 67, 78, 90, 104}

func (i Format) String() string {
	i -= -1
	if i < 0 || i >= Format(len(_Format_index)-1) {
		return "Format(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _Format_name[_Format_index[i]:_Format_index[i+1]]
}
