// Code generated by "stringer -type=Format -trimprefix=Format"; DO NOT EDIT.

package surface

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FormatARGB32-0]
	_ = x[FormatRGB24-1]
	_ = x[FormatA8-2]
	_ = x[FormatA1-3]
	_ = x[FormatRGB16_565-4]
	_ = x[FormatRGB30-5]
	_ = x[FormatInvalid - -1]
}

const _Format_name = "InvalidARGB32RGB24A8A1RGB16_565RGB30"

var _Format_index = [...]uint8{0, 7, 13, 18, 20, 22, 31, 36}

func (i Format) String() string {
	i -= -1
	if i < 0 || i >= Format(len(_Format_index)-1) {
		return "Format(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _Format_name[_Format_index[i]:_Format_index[i+1]]
}
