// Code generated by "stringer -type=SVGUnit"; DO NOT EDIT.

//go:build !nosvg

package surface

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SVGUnitUser-0]
	_ = x[SVGUnitEm-1]
	_ = x[SVGUnitEx-2]
	_ = x[SVGUnitPx-3]
	_ = x[SVGUnitIn-4]
	_ = x[SVGUnitCm-5]
	_ = x[SVGUnitMm-6]
	_ = x[SVGUnitPt-7]
	_ = x[SVGUnitPc-8]
	_ = x[SVGUnitPercent-9]
}

const _SVGUnit_name = "SVGUnitUserSVGUnitEmSVGUnitExSVGUnitPxSVGUnitInSVGUnitCmSVGUnitMmSVGUnitPtSVGUnitPcSVGUnitPercent"

var _SVGUnit_index = [...]uint8{0, 11, 20, 29, 38, 47, 56, 65, 74, 83, 97}

func (i SVGUnit) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_SVGUnit_index)-1 {
		return "SVGUnit(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SVGUnit_name[_SVGUnit_index[idx]:_SVGUnit_index[idx+1]]
}
