// Code generated by "stringer -type=SVGVersion -tags !nosvg"; DO NOT EDIT.

//go:build !nosvg

package surface

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SVGVersion11-0]
	_ = x[SVGVersion12-1]
}

const _SVGVersion_name = "SVGVersion11SVGVersion12"

var _SVGVersion_index = [...]uint8{0, 12, 24}

func (i SVGVersion) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_SVGVersion_index)-1 {
		return "SVGVersion(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SVGVersion_name[_SVGVersion_index[idx]:_SVGVersion_index[idx+1]]
}
