// Code generated by "stringer -type=Slant"; DO NOT EDIT.

package font

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SlantNormal-0]
	_ = x[SlantItalic-1]
	_ = x[SlantOblique-2]
}

const _Slant_name = "SlantNormalSlantItalicSlantOblique"

var _Slant_index = [...]uint8{0, 11, 22, 34}

func (i Slant) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Slant_index)-1 {
		return "Slant(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Slant_name[_Slant_index[idx]:_Slant_index[idx+1]]
}
