// Code generated by "stringer -type=Weight"; DO NOT EDIT.

package font

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WeightNormal-0]
	_ = x[WeightBold-1]
}

const _Weight_name = "WeightNormalWeightBold"

var _Weight_index = [...]uint8{0, 12, 22}

func (i Weight) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Weight_index)-1 {
		return "Weight(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Weight_name[_Weight_index[idx]:_Weight_index[idx+1]]
}
