// Code generated by "stringer -type=FillRule"; DO NOT EDIT.

package context

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FillRuleWinding-0]
	_ = x[FillRuleEvenOdd-1]
}

const _FillRule_name = "FillRuleWindingFillRuleEvenOdd"

var _FillRule_index = [...]uint8{0, 15, 30}

func (i FillRule) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_FillRule_index)-1 {
		return "FillRule(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FillRule_name[_FillRule_index[idx]:_FillRule_index[idx+1]]
}
