// Code generated by "stringer -type=LineJoin"; DO NOT EDIT.

package context

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LineJoinMiter-0]
	_ = x[LineJoinRound-1]
	_ = x[LineJoinBevel-2]
}

const _LineJoin_name = "LineJoinMiterLineJoinRoundLineJoinBevel"

var _LineJoin_index = [...]uint8{0, 13, 26, 39}

func (i LineJoin) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_LineJoin_index)-1 {
		return "LineJoin(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LineJoin_name[_LineJoin_index[idx]:_LineJoin_index[idx+1]]
}
