// Code generated by "stringer -type=LineCap"; DO NOT EDIT.

package context

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LineCapButt-0]
	_ = x[LineCapRound-1]
	_ = x[LineCapSquare-2]
}

const _LineCap_name = "LineCapButtLineCapRoundLineCapSquare"

var _LineCap_index = [...]uint8{0, 11, 23, 36}

func (i LineCap) String() string {
	if i < 0 || i >= LineCap(len(_LineCap_index)-1) {
		return "LineCap(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LineCap_name[_LineCap_index[i]:_LineCap_index[i+1]]
}
