// Code generated by "stringer -type=Operator"; DO NOT EDIT.

package context

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OperatorClear-0]
	_ = x[OperatorSource-1]
	_ = x[OperatorOver-2]
	_ = x[OperatorIn-3]
	_ = x[OperatorOut-4]
	_ = x[OperatorAtop-5]
	_ = x[OperatorDest-6]
	_ = x[OperatorDestOver-7]
	_ = x[OperatorDestIn-8]
	_ = x[OperatorDestOut-9]
	_ = x[OperatorDestAtop-10]
	_ = x[OperatorXor-11]
	_ = x[OperatorAdd-12]
	_ = x[OperatorSaturate-13]
	_ = x[OperatorMultiply-14]
	_ = x[OperatorScreen-15]
	_ = x[OperatorOverlay-16]
	_ = x[OperatorDarken-17]
	_ = x[OperatorLighten-18]
	_ = x[OperatorColorDodge-19]
	_ = x[OperatorColorBurn-20]
	_ = x[OperatorHardLight-21]
	_ = x[OperatorSoftLight-22]
	_ = x[OperatorDifference-23]
	_ = x[OperatorExclusion-24]
	_ = x[OperatorHslHue-25]
	_ = x[OperatorHslSaturation-26]
	_ = x[OperatorHslColor-27]
	_ = x[OperatorHslLuminosity-28]
}

const _Operator_name = "OperatorClearOperatorSourceOperatorOverOperatorInOperatorOutOperatorAtopOperatorDestOperatorDestOverOperatorDestInOperatorDestOutOperatorDestAtopOperatorXorOperatorAddOperatorSaturateOperatorMultiplyOperatorScreenOperatorOverlayOperatorDarkenOperatorLightenOperatorColorDodgeOperatorColorBurnOperatorHardLightOperatorSoftLightOperatorDifferenceOperatorExclusionOperatorHslHueOperatorHslSaturationOperatorHslColorOperatorHslLuminosity"

var _Operator_index = [...]uint16{0, 13, 27, 39, 49, 60, 72, 84, 100, 114, 129, 145, 156, 167, 183, 199, 213, 228, 242, 257, 275, 292, 309, 326, 344, 361, 375, 396, 412, 433}

func (i Operator) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Operator_index)-1 {
		return "Operator(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Operator_name[_Operator_index[idx]:_Operator_index[idx+1]]
}
