// Code generated by "stringer -type=Status"; DO NOT EDIT.

package status

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Success-0]
	_ = x[NoMemory-1]
	_ = x[InvalidRestore-2]
	_ = x[InvalidPopGroup-3]
	_ = x[NoCurrentPoint-4]
	_ = x[InvalidMatrix-5]
	_ = x[InvalidStatus-6]
	_ = x[NullPointer-7]
	_ = x[InvalidString-8]
	_ = x[InvalidPathData-9]
	_ = x[ReadError-10]
	_ = x[WriteError-11]
	_ = x[SurfaceFinished-12]
	_ = x[SurfaceTypeMismatch-13]
	_ = x[PatternTypeMismatch-14]
	_ = x[InvalidContent-15]
	_ = x[InvalidFormat-16]
	_ = x[InvalidVisual-17]
	_ = x[FileNotFound-18]
	_ = x[InvalidDash-19]
	_ = x[InvalidDscComment-20]
	_ = x[InvalidIndex-21]
	_ = x[ClipNotRepresentable-22]
	_ = x[TempFileError-23]
	_ = x[InvalidStride-24]
	_ = x[FontTypeMismatch-25]
	_ = x[UserFontImmutable-26]
	_ = x[UserFontError-27]
	_ = x[NegativeCount-28]
	_ = x[InvalidClusters-29]
	_ = x[InvalidSlant-30]
	_ = x[InvalidWeight-31]
	_ = x[InvalidSize-32]
	_ = x[UserFontNotImplemented-33]
	_ = x[DeviceTypeMismatch-34]
	_ = x[DeviceError-35]
	_ = x[InvalidMeshConstruction-36]
	_ = x[DeviceFinished-37]
	_ = x[JBig2GlobalMissing-38]
	_ = x[PngError-39]
	_ = x[FreetypeError-40]
	_ = x[Win32GdiError-41]
	_ = x[TagError-42]
	_ = x[DWriteError-43]
	_ = x[SvgFontError-44]
	_ = x[LastStatus-45]
}

const _Status_name = "SuccessNoMemoryInvalidRestoreInvalidPopGroupNoCurrentPointInvalidMatrixInvalidStatusNullPointerInvalidStringInvalidPathDataReadErrorWriteErrorSurfaceFinishedSurfaceTypeMismatchPatternTypeMismatchInvalidContentInvalidFormatInvalidVisualFileNotFoundInvalidDashInvalidDscCommentInvalidIndexClipNotRepresentableTempFileErrorInvalidStrideFontTypeMismatchUserFontImmutableUserFontErrorNegativeCountInvalidClustersInvalidSlantInvalidWeightInvalidSizeUserFontNotImplementedDeviceTypeMismatchDeviceErrorInvalidMeshConstructionDeviceFinishedJBig2GlobalMissingPngErrorFreetypeErrorWin32GdiErrorTagErrorDWriteErrorSvgFontErrorLastStatus"

var _Status_index = [...]uint16{0, 7, 15, 29, 44, 58, 71, 84, 95, 108, 123, 132, 142, 157, 176, 195, 209, 222, 235, 247, 258, 275, 287, 307, 320, 333, 349, 366, 379, 392, 407, 419, 432, 443, 465, 483, 494, 517, 531, 549, 557, 570, 583, 591, 602, 614, 624}

func (i Status) String() string {
	if i < 0 || i >= Status(len(_Status_index)-1) {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}
