// Code generated by "stringer -type=Extend -trimprefix=Extend"; DO NOT EDIT.

package pattern

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ExtendNone-0]
	_ = x[ExtendRepeat-1]
	_ = x[ExtendReflect-2]
	_ = x[ExtendPad-3]
}

const _Extend_name = "NoneRepeatReflectPad"

var _Extend_index = [...]uint8{0, 4, 10, 17, 20}

func (i Extend) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Extend_index)-1 {
		return "Extend(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Extend_name[_Extend_index[idx]:_Extend_index[idx+1]]
}
