// Code generated by "stringer -type=Filter -trimprefix=Filter"; DO NOT EDIT.

package pattern

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FilterFast-0]
	_ = x[FilterGood-1]
	_ = x[FilterBest-2]
	_ = x[FilterNearest-3]
	_ = x[FilterBilinear-4]
}

const _Filter_name = "FastGoodBestNearestBilinear"

var _Filter_index = [...]uint8{0, 4, 8, 12, 19, 27}

func (i Filter) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Filter_index)-1 {
		return "Filter(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Filter_name[_Filter_index[idx]:_Filter_index[idx+1]]
}
