// Code generated by "stringer -type=PatternType -trimprefix=PatternType"; DO NOT EDIT.

package pattern

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PatternTypeSolid-0]
	_ = x[PatternTypeSurface-1]
	_ = x[PatternTypeLinear-2]
	_ = x[PatternTypeRadial-3]
	_ = x[PatternTypeMesh-4]
	_ = x[PatternTypeRasterSource-5]
}

const _PatternType_name = "SolidSurfaceLinearRadialMeshRasterSource"

var _PatternType_index = [...]uint8{0, 5, 12, 18, 24, 28, 40}

func (i PatternType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_PatternType_index)-1 {
		return "PatternType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PatternType_name[_PatternType_index[idx]:_PatternType_index[idx+1]]
}
